# fly.toml app configuration file generated for pythonprodjango on 2023-11-12T16:25:52-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pythonprodjango"
primary_region = "gru"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"
  DEBUG = false

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

[deploy]
  release_command = "./deploy.sh"
