name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Copia os arquivos do repositório
        uses: actions/checkout@v4

      - name: Instalar pipenv
        run: pip install -q pipenv

      - name: Instalar dependências
        run: pipenv sync -d

      - name: Rodar o flake8
        run: pipenv run flake8